plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'br.com.houpper'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
    withJavadocJar()
}

dependencies {
    testImplementation libs.junit
    api libs.commons.math3
    implementation libs.guava
}

apply from: "gradle/scripts/build-info.gradle"